# Generated by Django 5.1.2 on 2024-11-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
