# Generated by Django 5.1.2 on 2024-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, choices=[('MATH', 'Math'), ('ENGLISH', 'English'), ('ENGINEERING', 'Engineering'), ('SCIENCE', 'Science'), ('HISTORY', 'History')], max_length=100, null=True),
        ),
    ]
