# Generated by Django 5.1.2 on 2024-11-04 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='selected_subject',
            field=models.CharField(blank=True, choices=[('MATH', 'Math'), ('ENGLISH', 'English'), ('ENGINEERING', 'Engineering'), ('SCIENCE', 'Science'), ('HISTORY', 'History')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='selected_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='user.teacher'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
