# Generated by Django 5.1.2 on 2024-11-05 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('mark', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_records', to='user.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_records_by_teacher', to='user.teacher')),
            ],
            options={
                'unique_together': {('student', 'teacher', 'subject')},
            },
        ),
    ]
