# Generated by Django 5.1.2 on 2024-11-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_markrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkRecord',
        ),
    ]
